using System.Collections.Generic;
using System.IO;
using System.Text;
using DesignSystem.Runtime.Typography;
using UnityEditor;
using UnityEngine;
using UnityEngine.TextCore.Text;

namespace DesignSystem.Editor.Typography
{
    /// <summary>
    /// Writes the stylesheet that makes an imported family the design system's typeface.
    ///
    /// The font arrives as a design TOKEN, not as a property sprinkled across components:
    /// the sheet declares <c>--ds-font-100 … --ds-font-900</c>, points <c>.ds-root</c> at
    /// <c>var(--ds-font-body)</c>, and lets USS inheritance carry it to every text element in
    /// the panel. Nothing in the 42 components needs to change, and swapping the sheet swaps
    /// the whole system's typeface.
    ///
    /// It also finally settles two apologies left in <c>Typography.uss</c>. <c>.ds-h3</c> is
    /// commented "Semibold — pair with a Semibold font asset for accuracy" and
    /// <c>.ds-caption</c> "Medium — pair with a Medium font asset for fidelity". Those are not
    /// aspirations any more: with a real family imported, this sheet points them at the real
    /// 600 and 500 faces. It loads after <c>DesignSystem.uss</c>, so equal-specificity rules
    /// resolve in its favour by source order.
    /// </summary>
    public static class FontUssWriter
    {
        /// <summary>
        /// Emits <c>&lt;folder&gt;/&lt;Family&gt;.uss</c> and returns its asset path.
        /// </summary>
        /// <param name="upgradeTypeRamp">
        /// Point <c>.ds-h3</c> at 600 and <c>.ds-caption</c> at 500 when the family ships them.
        /// This is the design system's documented intent; turn it off to keep the type ramp
        /// strictly normal/bold.
        /// </param>
        public static string Write(DsFontFamily family, string folder, bool upgradeTypeRamp = true)
        {
            if (family == null) return null;

            var sb = new StringBuilder(2048);
            string slug = FontAssetFactory.Sanitize(family.familyName);

            sb.AppendLine("/* ============================================================================");
            sb.AppendLine($"   {family.familyName.ToUpperInvariant()} — GENERATED by Design System > Google Fonts.");
            sb.AppendLine("   Do not edit: this file is rewritten from the family asset on every import.");
            sb.AppendLine();
            sb.AppendLine("   Add it to your root AFTER DesignSystem.uss and the whole system changes");
            sb.AppendLine("   typeface. `-unity-font-definition` is inherited, so one declaration on");
            sb.AppendLine("   `.ds-root` reaches every text element below it.");
            sb.AppendLine("   ============================================================================ */");
            sb.AppendLine();

            // ---- tokens ----
            sb.AppendLine(":root {");

            var available = new List<int>();
            for (int bucket = 0; bucket < DsFontFamily.WeightCount; bucket++)
            {
                int weight = DsFontFamily.WeightOf(bucket);
                var face = family.weights != null && bucket < family.weights.Length ? family.weights[bucket] : null;
                if (!face) continue;

                available.Add(weight);
                sb.AppendLine($"    --ds-font-{weight}: {Reference(face)};");
            }

            if (available.Count == 0)
            {
                Debug.LogError($"[DsFonts] '{family.familyName}' has no upright weights; nothing to write.");
                return null;
            }

            for (int bucket = 0; bucket < DsFontFamily.WeightCount; bucket++)
            {
                var face = family.italics != null && bucket < family.italics.Length ? family.italics[bucket] : null;
                if (!face) continue;

                sb.AppendLine($"    --ds-font-{DsFontFamily.WeightOf(bucket)}-italic: {Reference(face)};");
            }

            // The one token the rest of the design system actually reads.
            var body = family.Regular;
            sb.AppendLine();
            sb.AppendLine("    /* The active typeface. Everything below resolves through this. */");
            sb.AppendLine($"    --ds-font-body: {Reference(body)};");
            sb.AppendLine("}");
            sb.AppendLine();

            // ---- the one rule that changes the whole system ----
            sb.AppendLine("/* Inherited by every TextElement in the panel. */");
            sb.AppendLine(".ds-root {");
            sb.AppendLine("    -unity-font-definition: var(--ds-font-body);");
            sb.AppendLine("}");
            sb.AppendLine();

            // The dropdown popup is parented at PANEL scope, as a sibling of the document root,
            // so it never inherits from `.ds-root`. Without this it would keep rendering in
            // Unity's default font while everything else changed.
            sb.AppendLine("/* The dropdown popup is a sibling of the document root, not a child, so it");
            sb.AppendLine("   inherits nothing from .ds-root and has to be told separately. */");
            sb.AppendLine(".unity-base-dropdown__container-outer {");
            sb.AppendLine("    -unity-font-definition: var(--ds-font-body);");
            sb.AppendLine("}");
            sb.AppendLine();

            // ---- weight utilities ----
            sb.AppendLine("/* UI Toolkit has no `font-weight`; it has normal and bold and nothing else.");
            sb.AppendLine("   These reach the in-between faces the only way USS allows — by pointing");
            sb.AppendLine("   `-unity-font-definition` at a different FontAsset. They reset");
            sb.AppendLine("   `-unity-font-style` because the face already IS the weight, and asking");
            sb.AppendLine("   TextCore to embolden a real Bold smears a synthetic dilation over it. */");

            foreach (int weight in available)
            {
                sb.AppendLine($".ds-weight-{weight} {{");
                sb.AppendLine($"    -unity-font-definition: var(--ds-font-{weight});");
                sb.AppendLine("    -unity-font-style: normal;");
                sb.AppendLine("}");
            }

            sb.AppendLine();

            // ---- type ramp ----
            if (upgradeTypeRamp)
            {
                bool has600 = available.Contains(600);
                bool has500 = available.Contains(500);

                if (has600 || has500)
                {
                    sb.AppendLine("/* The type ramp, at the weights it was always specified at. Typography.uss");
                    sb.AppendLine("   asks for Semibold on .ds-h3 and Medium on .ds-caption and settles for");
                    sb.AppendLine("   bold, because with no font family there is no such face to reach for. */");

                    if (has600)
                    {
                        sb.AppendLine(".ds-h3 {");
                        sb.AppendLine("    -unity-font-definition: var(--ds-font-600);");
                        sb.AppendLine("    -unity-font-style: normal;");
                        sb.AppendLine("}");
                    }

                    if (has500)
                    {
                        sb.AppendLine(".ds-caption, .ds-section__title {");
                        sb.AppendLine("    -unity-font-definition: var(--ds-font-500);");
                        sb.AppendLine("    -unity-font-style: normal;");
                        sb.AppendLine("}");
                    }

                    sb.AppendLine();
                }
            }

            string path = $"{folder}/{slug}.uss";
            File.WriteAllText(path, sb.ToString());
            AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceSynchronousImport);

            return path;
        }

        /// <summary>
        /// A USS value that resolves to this FontAsset. Prefers <c>resource()</c>, which is what
        /// the rest of the design system uses for icons and which survives the asset being moved
        /// inside its Resources folder. Falls back to a GUID-based <c>url()</c> when the font
        /// lives outside Resources, so an import into any folder still produces a working sheet.
        /// </summary>
        public static string Reference(FontAsset face)
        {
            if (!face) return "initial";

            string path = AssetDatabase.GetAssetPath(face);

            const string marker = "/Resources/";
            int i = path.IndexOf(marker, System.StringComparison.Ordinal);
            if (i >= 0)
            {
                string rel = path.Substring(i + marker.Length);
                rel = rel.Substring(0, rel.Length - Path.GetExtension(rel).Length);
                return $"resource(\"{rel}\")";
            }

            if (AssetDatabase.TryGetGUIDAndLocalFileIdentifier(face, out string guid, out long fileId))
                return $"url(\"project://database/{path}?fileID={fileId}&guid={guid}&type=2#{face.name}\")";

            return "initial";
        }
    }
}
